### ISSUE TITLE
Error at @ line 75.

### ISSUE THREAD

**Issue by Genesis-Nova** [z16/Addons#3]
Recently attempting to load Opensesame and whenever it attempts to open a door it's giving me this error.

attempt to call field 'outgoing' (a nil value) 

I've poked around the packets/fields.lua which I'm pretty sure it's attempting to call but didn't come up with anything.

Sorry for the hassle.

**Comment by z16** [comment]
No hassle, that's what this tracker is for! I'll take a look in a bit.

**Comment by z16** [comment]
Should be fixed, thanks for pointing it out.
