### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sebyg666** [z16/Addons#4]
hi z16, ive been using this handy little addon for a while now, but i think it needs an update. i get a few issues and i think it misses some packets due to errors.

eg of one: 
line 293 bad argument #3 to 'format' (no value)

would be awsome to get a bit of an update. addon almost doesnt catch any packets in escha ruan, where i tried it. hope u can maybe find the time to fix it up, i cnt find an updated copy of this anywhere. thanks

**Comment by z16** [comment]
I know what the issue is about, it happens when a byte in the packet represents the % ASCII symbol. Since that is a formatting parameter in Lua (and I use nested formatting strings for performance reasons) it formats a string incorrectly. I'll see about fixing it soon.

**Comment by cairthenn** [comment]
I went to post here to find the issue exists!

Anyway, can add to line 190:

`chars[0x25] = '%%'`

**Comment by z16** [comment]
Fixed it using ^ that line. Thanks!
