### ISSUE TITLE
Packetviewer is unable to parse packets with boolean as types 

### ISSUE THREAD

**Issue by WinterSolstice8** [z16/Addons#8]
Outgoing 0x0B5 is defined as the following:

```
-- Speech
fields.outgoing[0x0B5] = L{
    {ctype='unsigned char',     label='Mode',               fn=chat},           -- 04
    {ctype='unsigned char',     label='GM',                 fn=bool},           -- 05
    {ctype='char*',             label='Message'},                               -- 06
}
```
the "GM" char is listed as bool and errors out on this line: https://github.com/z16/Addons/blob/master/PacketViewer/PacketViewer.lua#L384 `Attempt to concatenate local 'val' (a boolean value)`

I've made a change locally that may or may not be the right way to fix it. Let me know if you'd like me to PR it in, change as follows:

```
            if val ~= nil then
				if type(val) == "boolean" then
					packet['_f_' .. field.label] = ' (bool)'
				else
					packet['_f_' .. field.label] = ' (' .. val .. ')'
				end
            end
```

To test, load packetviewer, `//pv track o 0x05B` and try to use /say.

**Comment by z16** [comment]
It sounds like you have an older PV version. Check the link to line 384 you wrote above. Is it the same as in your local PV copy? Because the error you described should not be possible with the current code.

**Comment by WinterSolstice8** [comment]
Ah, you're right. I probably happened to get a copy of PacketViewer from an outdated clone repo somewhere else and not here. I've updated and confirmed it works fine.
